language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda2-latest-Linux-x86_64.sh -b
  - bash Miniconda3-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda2/bin:$HOME/miniconda3/bin:$PATH
# command to install dependencies
install:
  - pip2 install -r requirements.txt
  - pip2 install .
  - pip3 install -r requirements.txt
  - pip3 install .
# command to run tests
script: nosetests
# Branches to build
branches:
  only:
    - master
    - develop