language: python
sudo: required
python:
  - "2.7"
  - "3.5"
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib g++ cython
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: nosetests
# Branches to build
branches:
  only:
    - master
    - develop