language: python
sudo: required
python:
  - "2.7"
  - "3.5"
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - cython
# command to install dependencies
install:
  - pip install mpmath --no-deps
  - pip install sympy --no-deps
  - python setup.py install
# command to run tests
script: nosetests
# Branches to build
branches:
  only:
    - master
    - develop