"""
CMakeLists.txt templates.

:copyright: Copyright 2013 - now, see AUTHORS.
:license: GPLv2, see LICENSE for details.
"""

# Linux, Seq or OMP
linux_omp_template = """# CMakeLists.txt generated by ANNarchy
cmake_minimum_required(VERSION 3.17)

set(CORE_NAME "ANNarchyCore%(net_id)s")
set(WRAPPER_NAME "ANNarchyWrapper%(net_id)s")

set(CMAKE_CXX_COMPILER "%(compiler)s")

# Reset global settings as only target_compile_options() should be used
set(CMAKE_CXX_FLAGS "")
set(CMAKE_CXX_FLAGS_RELEASE "")
set(CMAKE_CXX_FLAGS_DEBUG "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "")
set(CMAKE_CXX_FLAGS_MINSIZEREL "")

# Define the Project
project(${WRAPPER_NAME} LANGUAGES CXX)

# Find Python and add include paths
find_package(Python COMPONENTS Interpreter Development NumPy)
if (Python_FOUND)
include_directories(
    ${Python_INCLUDE_DIRS}
    ${Python_NumPy_INCLUDE_DIRS}
)
endif()

# Detect the installed nanobind package and import it into CMake
# see also: https://nanobind.readthedocs.io/en/latest/building.html
execute_process(
    COMMAND "${Python_EXECUTABLE}" -m nanobind --cmake_dir
    OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE NB_DIR
)
list(APPEND CMAKE_PREFIX_PATH "${NB_DIR}")
find_package(nanobind CONFIG REQUIRED)

# Additional paths (ANNarchy-related)
include_directories(
    %(annarchy_include)s
    %(thirdparty_include)s
)

#
# Simulation Core
#
add_library(${CORE_NAME} STATIC
    ${CORE_NAME}.cpp
)

# Set the required C++ standard
target_compile_features(${CORE_NAME} PUBLIC cxx_std_14)

option(USE_PROFILE "Enable profiling" OFF)

target_compile_options(${CORE_NAME} PRIVATE
    # debug configs
    $<$<CONFIG:Debug>:%(cpu_flags)s>

    # release configs
    $<$<CONFIG:Release>:%(cpu_flags)s>
    $<$<AND:$<CONFIG:Release>,$<BOOL:${USE_PROFILE}>>:-g>
)

target_compile_definitions(${CORE_NAME} PRIVATE
    $<$<CONFIG:Release>:NDEBUG>
)

# Check if OpenMP is available and enable it.
find_package(OpenMP)
if(OpenMP_CXX_FOUND)
    target_link_libraries(${CORE_NAME} PUBLIC OpenMP::OpenMP_CXX)
endif()

# Use -fPIC
set_target_properties(${CORE_NAME} PROPERTIES
    POSITION_INDEPENDENT_CODE ON
)

#
# Nanobind Wrapper
#
nanobind_add_module(
    # Target name
    ${WRAPPER_NAME}
    NB_DOMAIN ${WRAPPER_NAME}
    # source files (will trigger above command)
    ${WRAPPER_NAME}.cpp
)

target_compile_options(${WRAPPER_NAME} PRIVATE
    # debug configs
    $<$<CONFIG:Debug>:-O0 -g>
    # release configs
    $<$<CONFIG:Release>:-O3>
)

target_compile_definitions(${WRAPPER_NAME} PRIVATE
    $<$<CONFIG:Release>:NDEBUG>
)

target_link_libraries(${WRAPPER_NAME} PRIVATE ${CORE_NAME})

# Nanobind generates by default ${WRAPPER_NAME}.cpython[version]-...
# we need to shorten that for easier handling.
set_target_properties(${WRAPPER_NAME} PROPERTIES SUFFIX ".so")

# After successful compilation move the shared library
add_custom_command(
    TARGET ${WRAPPER_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy ${WRAPPER_NAME}.so ../../
)
"""

# Linux, CUDA
linux_cuda_template = """# CMakeLists.txt generated by ANNarchy
cmake_minimum_required(VERSION 3.17)

set(CORE_NAME "ANNarchyCore%(net_id)s")
set(WRAPPER_NAME "ANNarchyWrapper%(net_id)s")

set(CMAKE_CXX_COMPILER "%(compiler)s")

# Reset global settings as only target_compile_options() should be used
set(CMAKE_CXX_FLAGS "")
set(CMAKE_CXX_FLAGS_RELEASE "")
set(CMAKE_CXX_FLAGS_DEBUG "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "")
set(CMAKE_CXX_FLAGS_MINSIZEREL "")

if (CMAKE_VERSION GREATER_EQUAL 3.18)
%(set_cuda_arch)s
endif()

# Define the Project
project(${WRAPPER_NAME} LANGUAGES CXX CUDA)

# Find Python and add include paths
find_package(Python COMPONENTS Interpreter Development NumPy)
if (Python_FOUND)
include_directories(
    ${Python_INCLUDE_DIRS}
    ${Python_NumPy_INCLUDE_DIRS}
)
endif()

# Detect the installed nanobind package and import it into CMake
# see also: https://nanobind.readthedocs.io/en/latest/building.html
execute_process(
    COMMAND "${Python_EXECUTABLE}" -m nanobind --cmake_dir
    OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE NB_DIR
)
list(APPEND CMAKE_PREFIX_PATH "${NB_DIR}")
find_package(nanobind CONFIG REQUIRED)

# Additional paths (ANNarchy-related)
include_directories(
    %(annarchy_include)s
    %(thirdparty_include)s
)

#
# Simulation Core
#
add_library(${CORE_NAME} STATIC
    ${CORE_NAME}.cpp
    ANNarchyKernel%(net_id)s.cu
)

# Set the required C++ standard
target_compile_features(${CORE_NAME} PUBLIC cxx_std_14)

option(USE_PROFILE "Enable profiling" OFF)

target_compile_options(${CORE_NAME} PRIVATE
    # debug configs
    $<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>: %(cpu_flags)s>
    $<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CUDA>>: %(gpu_flags)s -Xcompiler=%(xcompiler_flags)s>

    # release configs
    $<$<AND:$<CONFIG:Release>,$<COMPILE_LANGUAGE:CXX>>: %(cpu_flags)s>
    $<$<AND:$<CONFIG:Release>,$<COMPILE_LANGUAGE:CUDA>>: %(gpu_flags)s -Xcompiler=%(xcompiler_flags)s>
)

target_compile_definitions(${CORE_NAME} PRIVATE
    $<$<CONFIG:Release>:NDEBUG>
)

# Check if OpenMP is available and enable it.
find_package(OpenMP)
if(OpenMP_CXX_FOUND)
    target_link_libraries(${CORE_NAME} PUBLIC OpenMP::OpenMP_CXX)
endif()

# Use -fPIC
set_target_properties(${CORE_NAME} PROPERTIES
    POSITION_INDEPENDENT_CODE ON
)

#
# Nanobind Wrapper
#
nanobind_add_module(
    # Target name
    ${WRAPPER_NAME}
    NB_DOMAIN ${WRAPPER_NAME}
    # source files (will trigger above command)
    ${WRAPPER_NAME}.cpp
)

target_compile_options(${WRAPPER_NAME} PRIVATE
    # debug configs
    $<$<CONFIG:Debug>:-O0 -g>
    # release configs
    $<$<CONFIG:Release>:-O3>
)

target_compile_definitions(${WRAPPER_NAME} PRIVATE
    $<$<CONFIG:Release>:NDEBUG>
)

target_link_libraries(${WRAPPER_NAME} PRIVATE ${CORE_NAME})

# Nanobind generates by default ${WRAPPER_NAME}.cpython[version]-...
# we need to shorten that for easier handling.
set_target_properties(${WRAPPER_NAME} PROPERTIES SUFFIX ".so")

# After successful compilation move the shared library
add_custom_command(
    TARGET ${WRAPPER_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy ${WRAPPER_NAME}.so ../../
)
"""

# OSX, with clang, Seq only
osx_clang_template = """# CMakeLists.txt generated by ANNarchy
cmake_minimum_required(VERSION 3.17)

set(CORE_NAME "ANNarchyCore%(net_id)s")
set(MODULE_NAME "ANNarchyWrapper%(net_id)s")
set(CMAKE_CXX_COMPILER "%(compiler)s")

project(${MODULE_NAME} LANGUAGES CXX)

# Find Python and add include paths
find_package(Python COMPONENTS Interpreter Development NumPy)
if (Python_FOUND)
include_directories(
    ${Python_INCLUDE_DIRS}
    ${Python_NumPy_INCLUDE_DIRS}
)
endif()

# Detect the installed nanobind package and import it into CMake
# see also: https://nanobind.readthedocs.io/en/latest/building.html
execute_process(
    COMMAND "${Python_EXECUTABLE}" -m nanobind --cmake_dir
    OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE NB_DIR
)
list(APPEND CMAKE_PREFIX_PATH "${NB_DIR}")
find_package(nanobind CONFIG REQUIRED)

# Additional paths (ANNarchy-related)
include_directories(
    %(annarchy_include)s
    %(thirdparty_include)s
)

# Additional compiler flags (-fPIC will is added already)
add_compile_options(%(cpu_flags)s)
add_link_options(%(cpu_flags)s)

# Compile source files and generate shared library
nanobind_add_module(
    # Target name
    ${MODULE_NAME}
    NB_DOMAIN ${MODULE_NAME}
    # source files
    ${MODULE_NAME}.cpp
    ${CORE_NAME}.cpp
)

# Check if OpenMP is available and enable it.
find_package(OpenMP)
if(OpenMP_CXX_FOUND)
    target_link_libraries(${MODULE_NAME} PUBLIC OpenMP::OpenMP_CXX)
endif()

# Set the required C++ standard
target_compile_features(${MODULE_NAME} PUBLIC cxx_std_14)

# Nanobind generates by default ${MODULE_NAME}.cpython[version]-...
# we need to shorten that for easier handling.
set_target_properties(${MODULE_NAME} PROPERTIES SUFFIX ".dylib")

# After successful compilation move the shared library
add_custom_command(
    TARGET ${MODULE_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy ${MODULE_NAME}.dylib ../../
)
"""

# OSX, with gcc, OpenMP
osx_gcc_template = """# CMakeLists.txt generated by ANNarchy
cmake_minimum_required(VERSION 3.17)

set(CORE_NAME "ANNarchyCore%(net_id)s")
set(MODULE_NAME "ANNarchyWrapper%(net_id)s")
set(CMAKE_CXX_COMPILER "%(compiler)s")

project(${MODULE_NAME} LANGUAGES CXX)

# Find Python and add include paths
find_package(Python COMPONENTS Interpreter Development NumPy)
if (Python_FOUND)
include_directories(
    ${Python_INCLUDE_DIRS}
    ${Python_NumPy_INCLUDE_DIRS}
)
endif()

# Detect the installed nanobind package and import it into CMake
# see also: https://nanobind.readthedocs.io/en/latest/building.html
execute_process(
    COMMAND "${Python_EXECUTABLE}" -m nanobind --cmake_dir
    OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE NB_DIR
)
list(APPEND CMAKE_PREFIX_PATH "${NB_DIR}")
find_package(nanobind CONFIG REQUIRED)

# Additional paths (ANNarchy-related)
include_directories(
    %(annarchy_include)s
    %(thirdparty_include)s
)

# Additional compiler flags (-fPIC will is added already)
add_compile_options(%(cpu_flags)s)
add_link_options(%(cpu_flags)s)

# Compile source files and generate shared library
nanobind_add_module(
    # Target name
    ${MODULE_NAME}
    NB_DOMAIN ${MODULE_NAME}
    # source files
    ${MODULE_NAME}.cpp
    ${CORE_NAME}.cpp
)

# Check if OpenMP is available and enable it.
find_package(OpenMP)
if(OpenMP_CXX_FOUND)
    target_link_libraries(${MODULE_NAME} PUBLIC OpenMP::OpenMP_CXX)
endif()

# Set the required C++ standard
target_compile_features(${MODULE_NAME} PUBLIC cxx_std_14)

# Nanobind generates by default ${MODULE_NAME}.cpython[version]-...
# we need to shorten that for easier handling.
set_target_properties(${MODULE_NAME} PROPERTIES SUFFIX ".dylib")

# After successful compilation move the shared library
add_custom_command(
    TARGET ${MODULE_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy ${MODULE_NAME}.dylib ../../
)
"""
