all: 
	g++ main.cpp -O2 -g -std=c++0x -fpermissive -fopenmp -L./annarchy -lANNarchyCPP -o ANNarchy
	g++ main.cpp -O0 -g -std=c++0x -fpermissive -fopenmp -L./annarchy -lANNarchyCPP -o ANNarchyD
	
clean:
	rm -rf ANNarchy
